/** Declaration file generated by dts-gen */
/* tslint:disable */

export = require_reload;

declare function require_reload(name: any, ctx?: any): any;

declare namespace require_reload {
    const prototype: {
    };

    function emptyCache(context: any): void;

    function resolve(req: any, context: any): any;

    namespace emptyCache {
        const prototype: {
        };

    }

    namespace resolve {
        const prototype: {
        };

    }

}

